//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.AlbumProducts = new HashSet<AlbumProduct>();
            this.UserComments = new HashSet<UserComment>();
            this.UserLikes = new HashSet<UserLike>();
            this.VideoProducts = new HashSet<VideoProduct>();
        }
    
        public int Id { get; set; }
        public int ArtistProductId { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Thumbnail { get; set; }
        public int Views { get; set; }
    
        public virtual ICollection<AlbumProduct> AlbumProducts { get; set; }
        public virtual ArtistProduct ArtistProduct { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<UserLike> UserLikes { get; set; }
        public virtual ICollection<VideoProduct> VideoProducts { get; set; }
    }
}
