//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebNgheNhacDb1Entities : DbContext
    {
        public WebNgheNhacDb1Entities()
            : base("name=WebNgheNhacDb1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccountInfo> AccountInfoes { get; set; }
        public DbSet<Album> Albums { get; set; }
        public DbSet<AlbumProduct> AlbumProducts { get; set; }
        public DbSet<Artist> Artists { get; set; }
        public DbSet<ArtistProduct> ArtistProducts { get; set; }
        public DbSet<Playlist> Playlists { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserArtist> UserArtists { get; set; }
        public DbSet<UserComment> UserComments { get; set; }
        public DbSet<UserLike> UserLikes { get; set; }
        public DbSet<Video> Videos { get; set; }
        public DbSet<VideoProduct> VideoProducts { get; set; }
    }
}
