//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistProduct
    {
        public ArtistProduct()
        {
            this.Products = new HashSet<Product>();
            this.UserArtists = new HashSet<UserArtist>();
        }
    
        public int Id { get; set; }
        public int ArtistId { get; set; }
        public string StageName { get; set; }
        public string RealName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<UserArtist> UserArtists { get; set; }
    }
}
