//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AlbumProductId { get; set; }
        public string Name { get; set; }
        public string Desciption { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int Views { get; set; }
    
        public virtual AlbumProduct AlbumProduct { get; set; }
        public virtual User User { get; set; }
    }
}
