//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebNgheNhac.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Musics = new HashSet<Music>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual AlbumCategory AlbumCategory { get; set; }
        public virtual Product Product { get; set; }
        public virtual ICollection<Music> Musics { get; set; }
    }
}
