//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebNgheNhac.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Products = new HashSet<Product>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string StageName { get; set; }
        public string RealName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
    
        public virtual ArtistCategory ArtistCategory { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
