//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebNgheNhac.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistCategory
    {
        public ArtistCategory()
        {
            this.Artists = new HashSet<Artist>();
        }
    
        public int Id { get; set; }
        public string Tittle { get; set; }
        public int ParentId { get; set; }
        public int Level { get; set; }
    
        public virtual ICollection<Artist> Artists { get; set; }
    }
}
