//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWebNgheNhac.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Playlists = new HashSet<Playlist>();
            this.UserComments = new HashSet<UserComment>();
            this.Artists = new HashSet<Artist>();
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public int Info { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SecQuest1 { get; set; }
        public string SecAnswer1 { get; set; }
        public string SecQuest2 { get; set; }
        public string SecAnswer2 { get; set; }
    
        public virtual AccountInfo AccountInfo { get; set; }
        public virtual ICollection<Playlist> Playlists { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<Artist> Artists { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
